import { EquipmentItem, MuscleGroup, WorkoutTemplate, WorkoutType } from "@/lib/types";

export const STEP_GOAL = 10000;

export const WORKOUT_TYPES: WorkoutType[] = [
  "Push",
  "Pull",
  "Legs",
  "Upper",
  "Lower",
  "Football",
  "Active Recovery",
];

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Triceps",
  "Biceps",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Core",
];

export const DEFAULT_EQUIPMENT: EquipmentItem[] = [
  { id: "eq-barbell", name: "Barbell", category: "Free weights", available: true },
  { id: "eq-plates", name: "Plates up to 130kg", category: "Free weights", available: true },
  { id: "eq-bench", name: "Bench", category: "Bench", available: true },
  { id: "eq-rack", name: "Squat rack", category: "Rack", available: true },
  {
    id: "eq-db",
    name: "Adjustable dumbbells up to 32.5kg",
    category: "Free weights",
    available: true,
  },
  { id: "eq-dips", name: "Dip station", category: "Bodyweight", available: true },
];

export const WORKOUT_TEMPLATES: WorkoutTemplate[] = [
  {
    workoutType: "Push",
    durationMinutes: 25,
    notes: "Short pressing session focused on chest, shoulders, and triceps.",
    exercises: [
      {
        id: "push-bench",
        exerciseName: "Barbell bench press",
        muscleGroup: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Barbell", "Plates up to 130kg", "Bench", "Squat rack"],
        sets: 5,
        targetReps: 5,
        startingWeight: 60,
        notes: "Drive feet into floor and keep bar path consistent.",
      },
      {
        id: "push-press",
        exerciseName: "Dumbbell shoulder press",
        muscleGroup: ["Shoulders", "Triceps"],
        equipment: ["Adjustable dumbbells up to 32.5kg", "Bench"],
        sets: 3,
        targetReps: 8,
        startingWeight: 16,
        notes: "Use a seated position if you want extra stability.",
      },
      {
        id: "push-dips",
        exerciseName: "Dips",
        muscleGroup: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Dip station"],
        sets: 3,
        targetReps: 10,
        startingWeight: null,
        notes: "Beat total reps before you add weight.",
      },
      {
        id: "push-lateral",
        exerciseName: "Lateral raises",
        muscleGroup: ["Shoulders"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 2,
        targetReps: 15,
        startingWeight: 6,
        notes: "Smooth tempo and no body swing.",
      },
      {
        id: "push-skull",
        exerciseName: "Skull crushers",
        muscleGroup: ["Triceps"],
        equipment: ["Barbell", "Plates up to 130kg", "Bench"],
        sets: 2,
        targetReps: 12,
        startingWeight: 20,
        notes: "Lower behind forehead for elbow comfort.",
      },
    ],
  },
  {
    workoutType: "Pull",
    durationMinutes: 25,
    notes: "Rows and arm work with only home equipment.",
    exercises: [
      {
        id: "pull-row",
        exerciseName: "Barbell rows",
        muscleGroup: ["Back", "Biceps"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 4,
        targetReps: 8,
        startingWeight: 50,
        notes: "Keep torso set and row toward lower chest.",
      },
      {
        id: "pull-db-row",
        exerciseName: "One-arm dumbbell rows",
        muscleGroup: ["Back", "Biceps"],
        equipment: ["Adjustable dumbbells up to 32.5kg", "Bench"],
        sets: 3,
        targetReps: 10,
        startingWeight: 24,
        notes: "Use full range and pause at the top.",
      },
      {
        id: "pull-rear-delt",
        exerciseName: "Rear delt flyes",
        muscleGroup: ["Shoulders", "Back"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 2,
        targetReps: 15,
        startingWeight: 5,
        notes: "Stay strict and let shoulder blades move naturally.",
      },
      {
        id: "pull-curl",
        exerciseName: "Barbell curls",
        muscleGroup: ["Biceps"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 3,
        targetReps: 10,
        startingWeight: 20,
        notes: "Control the lowering phase.",
      },
      {
        id: "pull-hammer",
        exerciseName: "Hammer curls",
        muscleGroup: ["Biceps"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 2,
        targetReps: 12,
        startingWeight: 10,
        notes: "Keep elbows close to your sides.",
      },
    ],
  },
  {
    workoutType: "Legs",
    durationMinutes: 28,
    notes: "Heavy lower-body session with core work at the end.",
    exercises: [
      {
        id: "legs-squat",
        exerciseName: "Back squats",
        muscleGroup: ["Quads", "Glutes", "Core"],
        equipment: ["Barbell", "Plates up to 130kg", "Squat rack"],
        sets: 5,
        targetReps: 5,
        startingWeight: 70,
        notes: "Brace hard and own the bottom position.",
      },
      {
        id: "legs-rdl",
        exerciseName: "Romanian deadlifts",
        muscleGroup: ["Hamstrings", "Glutes", "Back"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 4,
        targetReps: 8,
        startingWeight: 60,
        notes: "Push hips back and keep bar close.",
      },
      {
        id: "legs-bss",
        exerciseName: "Bulgarian split squats",
        muscleGroup: ["Quads", "Glutes"],
        equipment: ["Adjustable dumbbells up to 32.5kg", "Bench"],
        sets: 2,
        targetReps: 10,
        startingWeight: 14,
        notes: "Use moderate load and smooth balance.",
      },
      {
        id: "legs-calf",
        exerciseName: "Standing calf raises",
        muscleGroup: ["Calves"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 3,
        targetReps: 15,
        startingWeight: 18,
        notes: "Pause at the top and bottom of each rep.",
      },
      {
        id: "legs-plank",
        exerciseName: "Weighted planks",
        muscleGroup: ["Core"],
        equipment: ["Plates up to 130kg"],
        sets: 3,
        targetReps: 1,
        startingWeight: 10,
        notes: "Treat target reps as 45-second holds.",
      },
    ],
  },
  {
    workoutType: "Upper",
    durationMinutes: 26,
    notes: "Compressed upper-body session when you want broad coverage.",
    exercises: [
      {
        id: "upper-bench",
        exerciseName: "Bench press",
        muscleGroup: ["Chest", "Triceps", "Shoulders"],
        equipment: ["Barbell", "Plates up to 130kg", "Bench", "Squat rack"],
        sets: 4,
        targetReps: 6,
        startingWeight: 62.5,
        notes: "Strong setup and fast concentric.",
      },
      {
        id: "upper-row",
        exerciseName: "Barbell rows",
        muscleGroup: ["Back", "Biceps"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 4,
        targetReps: 8,
        startingWeight: 50,
        notes: "Reset brace every set.",
      },
      {
        id: "upper-press",
        exerciseName: "Dumbbell shoulder press",
        muscleGroup: ["Shoulders", "Triceps"],
        equipment: ["Adjustable dumbbells up to 32.5kg", "Bench"],
        sets: 3,
        targetReps: 8,
        startingWeight: 16,
        notes: "Stop one rep before technical breakdown.",
      },
      {
        id: "upper-dips",
        exerciseName: "Dips",
        muscleGroup: ["Chest", "Triceps"],
        equipment: ["Dip station"],
        sets: 3,
        targetReps: 8,
        startingWeight: null,
        notes: "Add reps before external load.",
      },
      {
        id: "upper-curl",
        exerciseName: "Barbell curls",
        muscleGroup: ["Biceps"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 2,
        targetReps: 12,
        startingWeight: 20,
        notes: "Use strict form.",
      },
    ],
  },
  {
    workoutType: "Lower",
    durationMinutes: 24,
    notes: "Practical lower session with slightly less fatigue than full legs day.",
    exercises: [
      {
        id: "lower-squat",
        exerciseName: "Squats",
        muscleGroup: ["Quads", "Glutes", "Core"],
        equipment: ["Barbell", "Plates up to 130kg", "Squat rack"],
        sets: 4,
        targetReps: 6,
        startingWeight: 65,
        notes: "Work with crisp technique and controlled depth.",
      },
      {
        id: "lower-rdl",
        exerciseName: "Romanian deadlifts",
        muscleGroup: ["Hamstrings", "Glutes", "Back"],
        equipment: ["Barbell", "Plates up to 130kg"],
        sets: 3,
        targetReps: 8,
        startingWeight: 60,
        notes: "Hamstrings should do the work.",
      },
      {
        id: "lower-lunge",
        exerciseName: "Lunges",
        muscleGroup: ["Quads", "Glutes"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 2,
        targetReps: 10,
        startingWeight: 12,
        notes: "Alternate legs and keep stride consistent.",
      },
      {
        id: "lower-calf",
        exerciseName: "Calf raises",
        muscleGroup: ["Calves"],
        equipment: ["Adjustable dumbbells up to 32.5kg"],
        sets: 3,
        targetReps: 15,
        startingWeight: 18,
        notes: "Full stretch and pause.",
      },
      {
        id: "lower-core",
        exerciseName: "Core work",
        muscleGroup: ["Core"],
        equipment: ["Bodyweight"],
        sets: 3,
        targetReps: 12,
        startingWeight: null,
        notes: "Use dead bugs or hollow holds if needed.",
      },
    ],
  },
];
